server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
    datasource:
        name: test
        url: "jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf-8"
        username: test
        password: "000001"
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
        encoding:
          charset: UTF-8
          enabled: true
          force: true
    messages:
        encoding: UTF-8
    banner:
        charset: UTF-8

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zqh.springboot.demo.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql